# Generated by Django 5.2.8 on 2026-04-19 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraddress_city_useraddress_user_useraddress_zone'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ['-is_default_delivery', '-created_at']},
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='address_line1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='is_default',
            new_name='is_default_billing',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='address_line2',
            new_name='landmark',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_addresses', to='orders.pathaoarea'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='is_default_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='label',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'office'), ('other', 'Other')], default='home', max_length=20),
        ),
    ]
