# Generated by Django 5.2.8 on 2026-04-12 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0002_productvariantoption_product_discount_and_more'),
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Leave blank for site-wide vouchers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='vendor.vendorprofile'),
        ),
        migrations.AddField(
            model_name='cart',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='cart.voucher'),
        ),
        migrations.AddField(
            model_name='voucherusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucherusage',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='cart.voucher'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'variant')},
        ),
    ]
