"""
Django settings for market_hub project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e7iz@(00au76(vdf40adk+@dbtl_wvgf@=zbh+u2szp(z1zu68'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = ['http://localhost:3000', 'https://sisterlike-tastelessly-mike.ngrok-free.dev', 'https://observant-pebble-diary.ngrok-free.dev']


# Application definition

INSTALLED_APPS = [
    # Unfold must come before django.contrib.admin
    'unfold',
    'daphne',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'unfold.contrib.import_export',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'accounts',
    'admin_dashboard',
    'main',
    'vendor',
    'products',
    'cart',
    'orders',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'channels',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'market_hub.urls'
ASGI_APPLICATION = 'market_hub.asgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'market_hub.wsgi.application'


REDIS_URL = os.getenv('REDIS_URL')
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

AUTH_USER_MODEL = 'accounts.User'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')


# ─────────────────────────────────────────────────────────
# Django Unfold Admin
# ─────────────────────────────────────────────────────────
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    # ── Branding ────────────────────────────────────────────
    "SITE_TITLE": "MarketHub",
    "SITE_HEADER": "MarketHub Admin",
    "SITE_URL": "/",
    "SITE_ICON": None,
    "SITE_LOGO": None,
    "SITE_SYMBOL": "storefront",
    "SITE_FAVICONS": [],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": True,
    "BORDER_RADIUS": "6px",
    "ENVIRONMENT": "market_hub.settings.environment_callback",
    "DASHBOARD_CALLBACK": None,
    "THEME": "default",

    # ── Colors — oklch() format required by Unfold 0.83 ─────
    # Blue palette matching the storefront header colour
    "COLORS": {
        "primary": {
            "50":  "oklch(97.7% .014 254.128)",
            "100": "oklch(95.1% .031 253.572)",
            "200": "oklch(90.2% .063 254.128)",
            "300": "oklch(82.4% .119 253.572)",
            "400": "oklch(72.7% .183 254.128)",
            "500": "oklch(62.3% .214 253.572)",
            "600": "oklch(54.6% .215 253.572)",
            "700": "oklch(47.6% .193 253.572)",
            "800": "oklch(42.4% .155 253.572)",
            "900": "oklch(37.9% .120 252.435)",
            "950": "oklch(28.2% .091 267.935)",
        },
    },

    # ── Sidebar navigation ───────────────────────────────────
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Dashboard"),
                "collapsible": False,
                "items": [
                    {
                        "title": _("Overview"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": _("Site Settings"),
                        "icon": "settings",
                        "link": reverse_lazy("admin:orders_sitesettings_changelist"),
                    },
                ],
            },
            {
                "title": _("Catalog"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Categories"),
                        "icon": "category",
                        "link": reverse_lazy("admin:products_category_changelist"),
                    },
                    {
                        "title": _("Products"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:products_product_changelist"),
                    },
                    {
                        "title": _("Product Variants"),
                        "icon": "tune",
                        "link": reverse_lazy("admin:products_productvariant_changelist"),
                    },
                    {
                        "title": _("Reviews"),
                        "icon": "star",
                        "link": reverse_lazy("admin:products_productreview_changelist"),
                    },
                ],
            },
            {
                "title": _("Commerce"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Orders"),
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:orders_order_changelist"),
                    },
                    {
                        "title": _("Payments"),
                        "icon": "payments",
                        "link": reverse_lazy("admin:orders_payment_changelist"),
                    },
                    {
                        "title": _("Sub Orders"),
                        "icon": "account_tree",
                        "link": reverse_lazy("admin:orders_suborder_changelist"),
                    },
                    {
                        "title": _("Carts"),
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:cart_cart_changelist"),
                    },
                    {
                        "title": _("Vouchers"),
                        "icon": "local_offer",
                        "link": reverse_lazy("admin:cart_voucher_changelist"),
                    },
                ],
            },
            {
                "title": _("Users"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": reverse_lazy("admin:accounts_user_changelist"),
                    },
                    {
                        "title": _("Addresses"),
                        "icon": "location_on",
                        "link": reverse_lazy("admin:accounts_useraddress_changelist"),
                    },
                    {
                        "title": _("Customer Profiles"),
                        "icon": "people",
                        "link": reverse_lazy("admin:accounts_customerprofile_changelist"),
                    },
                ],
            },
            {
                "title": _("Vendors"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Vendor Profiles"),
                        "icon": "store",
                        "link": reverse_lazy("admin:vendor_vendorprofile_changelist"),
                    },
                ],
            },
            {
                "title": _("Content"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Home Banners"),
                        "icon": "view_carousel",
                        "link": reverse_lazy("admin:main_homebanner_changelist"),
                    },
                    {
                        "title": _("Delivery Charges"),
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:main_deliverycharge_changelist"),
                    },
                    {
                        "title": _("Wishlists"),
                        "icon": "favorite",
                        "link": reverse_lazy("admin:main_wishlist_changelist"),
                    },
                ],
            },
            {
                "title": _("Delivery & Logistics"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Pathao Cities"),
                        "icon": "location_city",
                        "link": reverse_lazy("admin:orders_pathaocity_changelist"),
                    },
                    {
                        "title": _("Pathao Zones"),
                        "icon": "map",
                        "link": reverse_lazy("admin:orders_pathaozone_changelist"),
                    },
                    {
                        "title": _("Pathao Areas"),
                        "icon": "place",
                        "link": reverse_lazy("admin:orders_pathaoarea_changelist"),
                    },
                    {
                        "title": _("Sync Progress"),
                        "icon": "sync",
                        "link": reverse_lazy("admin:orders_pathaosyncprogress_changelist"),
                    },
                ],
            },
            {
                "title": _("Auth & Permissions"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },

}


def environment_callback(request):
    """Show a coloured environment badge in the header."""
    if DEBUG:
        return [_("Development"), "warning"]
    return [_("Production"), "danger"]


# ─────────────────────────────────────────────────────────
# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Pathao API Configuration
PATHAO_CLIENT_ID = os.getenv('PATHAO_CLIENT_ID')
PATHAO_CLIENT_SECRET = os.getenv('PATHAO_CLIENT_SECRET')
PATHAO_API_BASE_URL = os.getenv('PATHAO_API_BASE_URL', 'https://api.pathao.com/v1/')
PATHAO_USERNAME = os.getenv('PATHAO_USERNAME')
PATHAO_PASSWORD = os.getenv('PATHAO_PASSWORD')


SSLCOMMERZ_STORE_ID = os.getenv('SSLCOMMERZ_STORE_ID')
SSLCOMMERZ_STORE_PASSWORD = os.getenv('SSLCOMMERZ_STORE_PASSWORD')
SSLCOMMERZ_SANDBOX = os.getenv('SSLCOMMERZ_SANDBOX', 'True') == 'True' 

if SSLCOMMERZ_SANDBOX:
    SSLCOMMERZ_API_URL = os.getenv('SSLCOMMERZ_SANDBOX_API_URL')
    SSLCOMMERZ_VALIDATION_URL = os.getenv('SSLCOMMERZ_SANDBOX_VALIDATION_URL')
else:
    SSLCOMMERZ_API_URL = os.getenv('SSLCOMMERZ_API_URL')
    SSLCOMMERZ_VALIDATION_URL = os.getenv('SSLCOMMERZ_VALIDATION_URL')

